CREATE TABLE "competitor_research_runs" (
  "id" text PRIMARY KEY NOT NULL,
  "lead_id" text NOT NULL,
  "run_id" text,
  "provider" text NOT NULL,
  "status" text DEFAULT 'DRAFT' NOT NULL,
  "outcome" text NOT NULL,
  "active_radius" text NOT NULL,
  "input_hash" text NOT NULL,
  "config_hash" text NOT NULL,
  "rules_version" text NOT NULL,
  "version" integer NOT NULL,
  "candidate_count" integer NOT NULL,
  "accepted_count" integer NOT NULL,
  "rejected_count" integer NOT NULL,
  "primary_radius_km" double precision NOT NULL,
  "fallback_radius_km" double precision NOT NULL,
  "max_selected" integer NOT NULL,
  "superseded_by" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "competitor_research_runs_provider_ck" CHECK (provider IN ('fixture','operator_csv')),
  CONSTRAINT "competitor_research_runs_status_ck" CHECK (status IN ('DRAFT','SUPERSEDED')),
  CONSTRAINT "competitor_research_runs_outcome_ck" CHECK (outcome IN ('RESEARCHED','INSUFFICIENT_COMPARABLE','NO_CANDIDATES_FOUND')),
  CONSTRAINT "competitor_research_runs_radius_ck" CHECK (active_radius IN ('PRIMARY_5KM','FALLBACK_10KM'))
);--> statement-breakpoint
CREATE TABLE "competitor_candidates" (
  "id" text PRIMARY KEY NOT NULL,
  "research_run_id" text NOT NULL,
  "row_index" integer NOT NULL,
  "provider_candidate_id" text,
  "business_name" text,
  "normalized_name" text,
  "raw_domain" text,
  "normalized_domain" text,
  "primary_category" text,
  "normalized_primary_category" text,
  "secondary_categories" jsonb NOT NULL,
  "normalized_services" jsonb NOT NULL,
  "latitude" double precision,
  "longitude" double precision,
  "city" text,
  "market" text,
  "language" text,
  "business_type" text,
  "parent_brand" text,
  "normalized_parent_brand" text,
  "branch_id" text,
  "brand_key" text NOT NULL,
  "distance_meters" double precision,
  "category_match" text,
  "comparability_score" integer,
  "confidence" text,
  "disposition" text NOT NULL,
  "rejection_reason" text,
  "reason_detail" text NOT NULL,
  "acceptance_rank" integer,
  "score_breakdown" jsonb NOT NULL,
  "gate_results" jsonb NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "competitor_candidates_disposition_ck" CHECK (disposition IN ('ACCEPTED','REJECTED')),
  CONSTRAINT "competitor_candidates_category_match_ck" CHECK (category_match IS NULL OR category_match IN ('EXACT','RELATED','WEAK','NONE')),
  CONSTRAINT "competitor_candidates_confidence_ck" CHECK (confidence IS NULL OR confidence IN ('HIGH','MEDIUM','LOW'))
);--> statement-breakpoint
ALTER TABLE "competitor_research_runs" ADD CONSTRAINT "competitor_research_runs_lead_id_leads_id_fk" FOREIGN KEY ("lead_id") REFERENCES "public"."leads"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "competitor_candidates" ADD CONSTRAINT "competitor_candidates_research_run_id_competitor_research_runs_id_fk" FOREIGN KEY ("research_run_id") REFERENCES "public"."competitor_research_runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "competitor_research_runs_lead_idx" ON "competitor_research_runs" ("lead_id");--> statement-breakpoint
CREATE UNIQUE INDEX "competitor_research_runs_idempotency_uk" ON "competitor_research_runs" ("lead_id","input_hash","config_hash");--> statement-breakpoint
CREATE UNIQUE INDEX "competitor_research_runs_version_uk" ON "competitor_research_runs" ("lead_id","version");--> statement-breakpoint
CREATE INDEX "competitor_candidates_run_idx" ON "competitor_candidates" ("research_run_id");
